23 f09 create admin panel edit existing product on live
KentuckySato/crazee-burger pull request #24
Opened 2023-09-14 23:12 UTC by KentuckySato

2023-09-15 16:58 UTC, vileaddev requested changes
Des choses à retirer et à renamer + des typages.

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AdminPanel/AddForm.tsx
> +
supprimer les espaces.

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AdminPanel/AddForm.tsx
> +
supprimer les espaces.

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Admin/Form/AdminForm.tsx
> +    .empty-image {
à bouger dans ImagePreview

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Menu/Menu.tsx
retirer les sauts de ligne inutiles.

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Menu/Menu.tsx
> +        if (productClickedOn) await setProductSelected(productClickedOn);
retirer le if mais garder l'instruction à l'intérieur du if et voir TS te sort une erreur ou non.

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Menu/Menu.tsx
> +        // useCase => we select Card A and delete Card B via close button. Then, the EditForm with all informations of Card A MUST be visible and intact.
c'est une histoire de stopPropagation que tu as résolu à la ligne 45, donc normalement, tu n'as plus besoin de rajouter ce commentaire.

2023-09-15 16:58 UTC, vileaddev commented on src/components/pages/order/Main/Menu/Menu.tsx
> +        titleFieldRef.current?.focus();
utile ?

2023-09-15 16:58 UTC, vileaddev commented on src/components/shared/Card.tsx
>      deleteCard?: boolean
```suggestion
    hasDeleteButton?: boolean
```

2023-09-15 16:58 UTC, vileaddev commented on src/components/shared/InputText.tsx
> +    autofocus?: boolean
inutile maintenant. A supprimer.

2023-09-15 16:58 UTC, vileaddev commented on src/components/shared/InputText.tsx
>      extraProps, inputStyle, containerStyle, version = 'normal',
extraProps est normalement laissé à la fin par usage.
Mais en typescript, on va éviter le extraProps car on veut explicitement typer CHACUN des props.

2023-09-15 16:58 UTC, vileaddev commented on src/enums/product.ts
> +export const EMPTY_PRODUCT = Object.freeze({
tu peux le typer lui aussi IProduct

2023-09-16 21:21 UTC, KentuckySato commented on src/components/pages/order/Main/Menu/Menu.tsx
> +        if (productClickedOn) await setProductSelected(productClickedOn);
Non je suis obligé de laisser le `if` sinon j'ai le message d'erreur laissé par TypeScript. De même lors du `yarn build` et de `vercel` j'ai la même erreur.

2023-09-16 21:41 UTC, KentuckySato commented on src/components/pages/order/Main/Admin/Form/AdminForm.tsx
> +    .empty-image {
Je vais supprimer cette règle CSS car je l'ai déjà mise dans `ImagePreview`.

2023-09-16 21:50 UTC, KentuckySato commented on src/components/pages/order/Main/Menu/Menu.tsx
> +        // useCase => we select Card A and delete Card B via close button. Then, the EditForm with all informations of Card A MUST be visible and intact.
Oui c'est ça. En fait j'ai voulu expliquer le code (pour moi plus tard) car quand je sélectionne un produit A puis je supprime un produit B, le formulaire EditForm se barre et je n'ai plus les informations du produit A et à la place j'ai le message `Cliquer sur un produit du menu pour le modifier`. Et en faisant la vérification de l'id du produit que l'on veut supprimer avec l'id du produit sélectionné, je garde les informations et le formulaire reste intact.

2023-09-16 22:29 UTC, KentuckySato commented on src/components/pages/order/Main/Menu/Menu.tsx
> +        titleFieldRef.current?.focus();
Oui car on perd le focus sur le champ `title` quand on supprime un autre produit que celui sélectionné. C'est dans le `F09 - Live AMA (2sur2)` (2:25:00), tu le met mais j'ai l'impression que tu vas l'enlever pour les prochains tickets. C'etait une suggestion d'une personne présente dans le live ama (yann).

2023-09-18 18:43 UTC, vileaddev approved these changes
PANEL ADMIN > FORM > TEXT INPUT > Eventuellement change le spacing à gauche du l'icon et quand c'est fait, tu regit push et merge direct après.

2023-09-19 13:48 UTC, KentuckySato reviewed
Tout est ok ! les changements ont été appliqués. @vileaddev je vais merger

2023-09-19 13:48 UTC, merged